### ISSUE TITLE
ansible jobstatement

### ISSUE THREAD

**Issue by phil34130** [IBM/ibm_zos_zosmf#76]
how can i enter a job statement on 2 records in an ansible playbook with z/OSMF collection ? i have looked at https://www.ibm.com/support/knowledgecenter/SSLTBW_2.2.0/com.ibm.zos.v2r2.izua700/izuprog_API_WorkflowCreateNew.htm  which says:
"For a workflow that submits a job, this property specifies the JOB statement JCL that is used in the job. This property can be null, or a list of JCL cards, each up to 72 characters long. Columns 1 and 2 of each record must be "//" or "/*" and the job name must be 1 to 8 characters." 
The variations i  have tried were not sucessful, like
workflow_job_statement: "//IZUWFJB JOB MSGCLASS=X,REGION=4M,NOTIFY=&SYSUID,
// MSGLEVEL=1"
The 2 records are appended on the same 1rst JOB CARD....
Could you post a sample how to achieve that, having a JOBCARD on 2 records with a continuation line.

**Comment by zosmf-Young** [comment]
Please put the **"\n"** between 2 records of job statement. For example:
```yml
workflow_job_statement: "//IZUWFJB JOB MSGCLASS=X,REGION=4M,NOTIFY=&SYSUID,\n//    MSGLEVEL=1"
```
Notice that there is a **"\n"** between "//IZUWFJB JOB MSGCLASS=X,REGION=4M,NOTIFY=&SYSUID," and "//    MSGLEVEL=1".

**Comment by phil34130** [comment]
excellent ! that did the trick...thank you
